// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/voca-test"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "post": {
                "description": "Register a new user in the system with the provided name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User registration details",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/wallets": {
            "post": {
                "description": "Register a new wallet for a specific user with a chosen currency.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallets"
                ],
                "summary": "Create a wallet for a user",
                "parameters": [
                    {
                        "description": "Wallet creation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.WalletCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Wallet created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Wallet"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/wallets/transfer": {
            "post": {
                "description": "Transfer funds from one wallet to another. Both wallets must use the same currency. Requires an idempotency key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallets"
                ],
                "summary": "Move money between same-currency wallets",
                "parameters": [
                    {
                        "description": "Transfer details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transfer successful",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request, currency mismatch, or insufficient balance",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/wallets/{id}": {
            "get": {
                "description": "Retrieve the current balance and status of a specific wallet.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallets"
                ],
                "summary": "Get wallet details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Wallet retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Wallet"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid wallet ID",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Wallet not found",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/wallets/{id}/pay": {
            "post": {
                "description": "Deduct funds from a wallet for a payment. Requires an idempotency key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallets"
                ],
                "summary": "Spend money from a wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payment details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Payment successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Wallet"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body, insufficient balance, or wallet ID",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/wallets/{id}/suspend": {
            "post": {
                "description": "Change a wallet status to SUSPENDED. Suspended wallets cannot perform transactions.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallets"
                ],
                "summary": "Suspend a wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Wallet suspended successfully",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid wallet ID",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/wallets/{id}/topup": {
            "post": {
                "description": "Add funds to a wallet. Requires an idempotency key to prevent duplicate transactions.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallets"
                ],
                "summary": "Top-up money to a wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Top-up details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TopUpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Top-up successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Wallet"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body or wallet ID",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/wallets/{id}/transactions": {
            "get": {
                "description": "Retrieve a list of all transactions (ledger entries) for a specific wallet, sorted by date.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallets"
                ],
                "summary": "Get wallet transaction history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Transaction type filter (TOPUP, PAYMENT, TRANSFER_IN, TRANSFER_OUT)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction history retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.LedgerEntry"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/util.PaginationMeta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid wallet ID",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.LedgerEntry": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "balance_after": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "reference_id": {
                    "type": "string"
                },
                "type": {
                    "description": "TOPUP, PAYMENT, TRANSFER_IN, TRANSFER_OUT",
                    "type": "string"
                },
                "wallet_id": {
                    "type": "string"
                }
            }
        },
        "models.PaymentRequest": {
            "type": "object",
            "required": [
                "amount",
                "idempotency_key"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "idempotency_key": {
                    "type": "string"
                }
            }
        },
        "models.TopUpRequest": {
            "type": "object",
            "required": [
                "amount",
                "idempotency_key"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "idempotency_key": {
                    "type": "string"
                }
            }
        },
        "models.TransferRequest": {
            "type": "object",
            "required": [
                "amount",
                "from_wallet_id",
                "idempotency_key",
                "to_wallet_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "from_wallet_id": {
                    "type": "string"
                },
                "idempotency_key": {
                    "type": "string"
                },
                "to_wallet_id": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.UserCreateRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Wallet": {
            "type": "object",
            "required": [
                "currency"
            ],
            "properties": {
                "balance": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "description": "ACTIVE, SUSPENDED",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "models.WalletCreateRequest": {
            "type": "object",
            "required": [
                "currency",
                "user_id"
            ],
            "properties": {
                "currency": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "util.APIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Actual payload for success"
                },
                "errors": {
                    "description": "Specific error details (e.g., validation)"
                },
                "message": {
                    "description": "General message",
                    "type": "string"
                },
                "meta": {
                    "description": "Pagination metadata",
                    "allOf": [
                        {
                            "$ref": "#/definitions/util.PaginationMeta"
                        }
                    ]
                },
                "status": {
                    "description": "\"success\" or \"error\"",
                    "type": "string"
                },
                "summary": {
                    "description": "Aggregated summary data"
                }
            }
        },
        "util.PaginationLinks": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "string"
                },
                "first": {
                    "type": "string"
                },
                "last": {
                    "type": "string"
                },
                "next": {
                    "type": "string"
                },
                "prev": {
                    "type": "string"
                }
            }
        },
        "util.PaginationMeta": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "links": {
                    "$ref": "#/definitions/util.PaginationLinks"
                },
                "per_page": {
                    "type": "integer"
                },
                "total_items": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Multi-Currency E-Wallet API",
	Description:      "This is a simplified multi-currency E-Wallet backend system implemented in Go using the Repository pattern, Gin framework, and PostgreSQL.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
